### ISSUE TITLE
t4p4s compilation issue

### ISSUE THREAD

**Issue by ztz1989** [P4ELTE/t4p4s#12] opened 2019-04-19 11:06 UTC
Dear authors of t4p4s, I am really interested in this project, so I am trying to build and test the performance of my testbed, but I encountered an issue when I ran the boostrap-t4p4s.sh. The output is posted below. My system runs Linux 4.8.0-41-generic #44~16.04.1-Ubuntu SMP. 

`
 $. ./bootstrap-t4p4s.sh

System has 48 cores; will use 48 jobs
Requesting root access...
Root access granted, starting...
Determining newest DPDK version...
Using DPDK version vsn[1]

Warning: wildcards not supported in HTTP.
--2019-04-19 12:57:49--  http://fast.dpdk.org/rel/dpdk-vsn[1].tar.xz
Resolving fast.dpdk.org (fast.dpdk.org)... 151.101.122.49
Connecting to fast.dpdk.org (fast.dpdk.org)|151.101.122.49|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-19 12:57:49 ERROR 404: Not Found.

Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:2 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease        
Hit:3 http://fr.archive.ubuntu.com/ubuntu xenial InRelease                                               
Get:4 http://fr.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                                         
Ign:5 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial InRelease                                                             
Hit:6 http://ppa.launchpad.net/webupd8team/sublime-text-2/ubuntu xenial InRelease                                    
Get:7 http://fr.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                       
Ign:8 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial Release                               
Ign:9 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 Packages                   
Ign:10 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main all Packages
Get:16 http://fr.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [938 kB]
Ign:12 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en 
Ign:14 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 Packages                            
Get:17 http://fr.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [814 kB]           
Ign:10 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main i386 Packages                                                    
Ign:11 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main all Packages                                                     
Ign:12 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en                                                   
Get:18 http://fr.archive.ubuntu.com/ubuntu xenial-updates/main amd64 DEP-11 Metadata [318 kB]                                        
Ign:14 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 DEP-11 Metadata                       
Ign:15 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main DEP-11 64x64 Icons                          
Ign:9 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 Packages           
Get:19 http://fr.archive.ubuntu.com/ubuntu xenial-updates/main DEP-11 64x64 Icons [232 kB]                                 
Ign:10 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main i386 Packages                                                       
Get:20 http://fr.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 DEP-11 Metadata [252 kB]             
Ign:11 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main all Packages                                    
Get:21 http://fr.archive.ubuntu.com/ubuntu xenial-updates/universe DEP-11 64x64 Icons [350 kB]                      
Ign:12 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en_US                          
Ign:13 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en                             
Get:22 http://fr.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 DEP-11 Metadata [5,960 B]          
Get:23 http://fr.archive.ubuntu.com/ubuntu xenial-updates/multiverse DEP-11 64x64 Icons [14.3 kB]                     
Get:24 http://fr.archive.ubuntu.com/ubuntu xenial-backports/main amd64 DEP-11 Metadata [3,328 B]                
Get:25 http://fr.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 DEP-11 Metadata [5,104 B]                 
Ign:14 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 DEP-11 Metadata  
Ign:15 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 Packages
Ign:10 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en
Ign:26 https://nexus.fd.io/content/repositories/fd.io.stable.1801.ubuntu.xenial.main ./ InRelease
Ign:14 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Err:9 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:10 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main i386 Packages
Ign:11 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main all Packages
Ign:12 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Ign:28 https://nexus.fd.io/content/repositories/fd.io.stable.1801.ubuntu.xenial.main ./ Release.gpg
Fetched 3,259 kB in 0s (3,272 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/boost-latest/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/boost-latest/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
[1]   Exit 100                sudo apt-get update && sudo apt-get -y install g++ git automake libtool libgc-dev bison flex libfl-dev libgmp-dev libboost-dev libboost-iostreams-dev pkg-config python python-scapy python-ipaddr tcpdump cmake python-setuptools libprotobuf-dev libnuma-dev curl
[2]   Exit 8                  [ ! -d "dpdk-${DPDK_VSN}" ] && wget http://fast.dpdk.org/rel/dpdk-$DPDK_FILEVSN.tar.xz && tar xJf dpdk-$DPDK_FILEVSN.tar.xz && rm dpdk-$DPDK_FILEVSN.tar.xz
[3]   Exit 1                  [ ! -d "protobuf" ] && git clone --recursive -b "${PROTOBUF_BRANCH}" https://github.com/google/protobuf
[4]-  Exit 1                  [ ! -d "p4c" ] && git clone --recursive https://github.com/p4lang/p4c && cd p4c && git checkout $P4C_COMMIT && git submodule update --init --recursive
[5]+  Exit 1                  [ ! -d t4p4s ] && git clone --recursive https://github.com/P4ELTE/t4p4s
ls: cannot access 'dpdk*vsn[1]*/': No such file or directory
make: *** No rule to make target 'install'.  Stop.
-bash: cd: protobuf: No such file or directory
-bash: ./autogen.sh: No such file or directory
-bash: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
-bash: cd: p4c: No such file or directory
-bash: ./bootstrap.sh: No such file or directory
-bash: cd: build: No such file or directory
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
ls: cannot access 'dpdk*vsn[1]*/': No such file or directory
-bash: ./t4p4s_environment_variables.sh: Permission denied
chmod: cannot access '//t4p4s_environment_variables.sh': No such file or directory
-bash: //t4p4s_environment_variables.sh: No such file or directory
Environment variable config is done
Environment variable config is saved in //t4p4s_environment_variables.sh
Your ~/.profile is not modified, as it already calls t4p4s_environment_variables.sh
-bash: cd: t4p4s: No such file or directory
`

Could you give me some hints about this problem?

**Comment by afressancourt** [comment] 2019-05-20 15:06
Hello,
I am having a similar problem. Could you tell us what we did wrong? Thanks in advance for your help

**Comment by irevoire** [comment] 2019-05-21 10:53
Well... It's not working here either.

I tried to fix your script here: #13 
It works on my machine so I'm not gonna refactor more, but I feel like there is still a lot of 'bug' in your script and absolutly no error handling

**Comment by kitlei-robert** [comment] 2019-05-22 09:25
I just became aware of this ticket. Fixed in 77a0dfe9299f09e19f3275a733280149301f1518; caused by a minor difference in `bash` dialects.

Note that you can force sequential bootstrap execution by invoking `PARALLEL_INSTALL=0 . ./bootstrap-t4p4s.sh`.

**Closed by kitlei-robert** 2019-05-22 09:25 UTC
